apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-quarkus
  name: hello-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-quarkus
  template:
    metadata:
      labels:
        app: hello-quarkus
    spec:
      containers:
        - name: hello-quarkus
          image: hello-quarkus
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
        - name: registry-sec
