apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hello-quarkus
  newName: ghcr.io/dicolasi/hello-quarkus
  newTag: 4eb06e84c4ff054b302575ab2ccdc6ae4541f6f7
