apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: dicolasi/hello-quarkus
  newName: ghcr.io/dicolasi/hello-quarkus
  newTag: v0.12.24
