apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-quarkus
  name: hello-quarkus-svc
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: hello-quarkus
  type: ClusterIP